#!/bin/bash

# PhantomOS Shell Commands Test Script
# This script demonstrates all the integrated shell commands

echo "PhantomOS Shell Commands Demo"
echo "============================"
echo ""
echo "Commands to test in PhantomOS:"
echo ""
echo "1. Basic Commands:"
echo "   help         # Show all available commands"
echo "   clear        # Clear the screen"
echo "   echo Hello   # Echo text"
echo "   version      # Show OS version"
echo "   pwd          # Show current directory"
echo ""
echo "2. Directory Commands:"
echo "   mkdir test   # Create a directory"
echo "   cd test      # Change to directory"
echo "   cd ..        # Go to parent directory"
echo "   cd /         # Go to root"
echo "   ls           # List directory contents"
echo "   tree         # Show directory tree"
echo "   rmdir test   # Remove empty directory"
echo ""
echo "3. File Commands:"
echo "   touch file.txt              # Create empty file"
echo "   write file.txt \"Hello World\" # Write text to file"
echo "   cat file.txt                # Display file contents"
echo "   stat file.txt               # Show file information"
echo "   cp file.txt copy.txt        # Copy file"
echo "   mv copy.txt renamed.txt     # Rename file"
echo "   rm renamed.txt              # Remove file"
echo ""
echo "4. Text Editor (vim-like):"
echo "   edit file.txt  # Open file in editor"
echo "   vi file.txt    # Same as edit (alias)"
echo ""
echo "   Editor Commands:"
echo "   - Normal Mode:"
echo "     i        # Enter insert mode"
echo "     a        # Enter insert mode after cursor"
echo "     o        # Open new line below"
echo "     h,j,k,l  # Move cursor (left, down, up, right)"
echo "     x        # Delete character"
echo "     dd       # Delete line"
echo "     :w       # Save file"
echo "     :q       # Quit (if no changes)"
echo "     :q!      # Force quit without saving"
echo "     :wq      # Save and quit"
echo ""
echo "   - Insert Mode:"
echo "     ESC      # Return to normal mode"
echo "     Type text normally"
echo "     Backspace to delete"
echo ""
echo "5. Advanced Usage:"
echo "   mkdir docs"
echo "   cd docs"
echo "   edit readme.txt    # Create and edit new file"
echo "   # Press 'i' to enter insert mode"
echo "   # Type: PhantomOS Documentation"
echo "   # Press ESC to return to normal mode"
echo "   # Type :wq to save and exit"
echo "   cat readme.txt     # View the file"
echo "   cd /"
echo "   tree               # See the full directory structure"
echo ""
echo "To test PhantomOS:"
echo "  make run     # Run in QEMU"
echo "  make debug   # Run with debugging" 