#!/bin/bash

echo "PhantomOS Text Editor Test Instructions"
echo "======================================="
echo ""
echo "1. Start PhantomOS:"
echo "   make run"
echo ""
echo "2. Test the editor with these commands:"
echo ""
echo "   # Create and edit a new file"
echo "   edit test.txt"
echo ""
echo "3. In the editor, test these operations:"
echo ""
echo "   NORMAL MODE (initial mode):"
echo "   - Press 'i' to enter INSERT mode"
echo "   - Press 'h/j/k/l' to move cursor"
echo "   - Press ':' to enter COMMAND mode"
echo ""
echo "   INSERT MODE:"
echo "   - Type text normally"
echo "   - Press ESC to return to NORMAL mode"
echo "   - Use arrow keys to navigate"
echo "   - Press Backspace to delete"
echo ""
echo "   COMMAND MODE:"
echo "   - Type 'w' and press Enter to save"
echo "   - Type 'q' and press Enter to quit"
echo "   - Type 'wq' and press Enter to save and quit"
echo "   - Press ESC to return to NORMAL mode"
echo ""
echo "4. After exiting the editor:"
echo "   cat test.txt  # View the saved file"
echo ""
echo "Tips:"
echo "- The editor shows line numbers on the left"
echo "- The status bar shows the filename and current mode"
echo "- Modified files show [+] in the status bar" 